IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'transaction')
CREATE TABLE [transaction](
[trxId] BIGINT IDENTITY(1000,1) NOT NULL,
[amount] NUMERIC(19, 2) NOT NULL,
[currency] NVARCHAR(3) NOT NULL,
[id] NVARCHAR(20) NOT NULL,
[bankref] NVARCHAR(20) NOT NULL,
[transactionId] NVARCHAR(20) NOT NULL,
[bookingDate] DATE NULL,
[postingDate] DATE NOT NULL,
[creditDebitIndicator] VARCHAR(4) NULL,
[ownAccountNumber] NVARCHAR(20) NULL,
[counterPartyAccount] BIGINT NOT NULL,
[detail1] NVARCHAR(50) NULL,
[detail2] NVARCHAR(50) NULL,
[detail3] NVARCHAR(50) NULL,
[detail4] NVARCHAR(50) NULL,
[productBankRef] NVARCHAR(50) NULL,
[transactionType] BIGINT NOT NULL,
[statement] BIGINT NOT NULL,
[constantSymbol] VARCHAR(10) NULL,
[specificSymbol] VARCHAR(10) NULL,
[variableSymbol] VARCHAR(10) NULL,
CONSTRAINT PK_transaction_trxId PRIMARY KEY (trxId))